export interface BeadColor {
  name: string;
  hex: string;
}

// Standard Perler solid colors (community-standard hex approximations).
export const PERLER_COLORS: BeadColor[] = [
  { name: "White", hex: "#F2F2F2" },
  { name: "Cream", hex: "#EEE8C0" },
  { name: "Pastel Yellow", hex: "#FAF178" },
  { name: "Yellow", hex: "#F5DF00" },
  { name: "Cheddar", hex: "#FFB700" },
  { name: "Butterscotch", hex: "#E39B3E" },
  { name: "Orange", hex: "#FF7300" },
  { name: "Hot Coral", hex: "#FF5A50" },
  { name: "Salmon", hex: "#FF8373" },
  { name: "Blush", hex: "#FF9497" },
  { name: "Peach", hex: "#F6C4B9" },
  { name: "Light Pink", hex: "#F7CAD7" },
  { name: "Pink", hex: "#E5619B" },
  { name: "Bubblegum", hex: "#E86BA8" },
  { name: "Magenta", hex: "#F0349A" },
  { name: "Raspberry", hex: "#AD3E6E" },
  { name: "Cranapple", hex: "#8A2D50" },
  { name: "Red", hex: "#C62A34" },
  { name: "Cherry", hex: "#A3132F" },
  { name: "Rust", hex: "#8F4034" },
  { name: "Light Brown", hex: "#9E6C40" },
  { name: "Brown", hex: "#59413B" },
  { name: "Tan", hex: "#CBA47E" },
  { name: "Sand", hex: "#E0C8A2" },
  { name: "Gold", hex: "#BE8C46" },
  { name: "Gray", hex: "#91969A" },
  { name: "Dark Gray", hex: "#55585C" },
  { name: "Light Gray", hex: "#BCBEC1" },
  { name: "Black", hex: "#2E2F32" },
  { name: "Pastel Lavender", hex: "#BFA9D9" },
  { name: "Lavender", hex: "#A78BC5" },
  { name: "Purple", hex: "#60408D" },
  { name: "Plum", hex: "#A44FA4" },
  { name: "Periwinkle", hex: "#6E82C2" },
  { name: "Pastel Blue", hex: "#7FA9DE" },
  { name: "Light Blue", hex: "#428ACD" },
  { name: "Blue", hex: "#2554A7" },
  { name: "Dark Blue", hex: "#263A75" },
  { name: "Toothpaste", hex: "#98D3CE" },
  { name: "Turquoise", hex: "#008BAB" },
  { name: "Parrot Green", hex: "#009171" },
  { name: "Dark Green", hex: "#1E6E48" },
  { name: "Evergreen", hex: "#3A5C43" },
  { name: "Green", hex: "#108551" },
  { name: "Bright Green", hex: "#4CB944" },
  { name: "Light Green", hex: "#65C297" },
  { name: "Kiwi Lime", hex: "#6EBE44" },
  { name: "Prickly Pear", hex: "#BFD73B" },
  { name: "Pastel Green", hex: "#82C785" },
  { name: "Fern", hex: "#729944" },
];
